server:
  port: 80

spring:
  application:
    name: cloud-order-service
  cloud:
    consul:
      host: 192.168.145.128
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
        prefer-ip-address: true