spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 50
  mvc:
    format:
      date: yyyy-MM-dd

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lq.mvcdemo.bean
  type-handlers-package: com.lq.mvcdemo.handler


#配置日志
logging:
  level:
    root: info
  com.lq.mvcdemo: debug