server:
  port: 3344
spring:
  application:
    name: cloud-config-center

  cloud:
    config:
      server:
        git:
          # Github上的git仓库uri
          # 使用git@github.com。。的uri需要添加username, password参数
          #uri: git@github.com:ordinarylq/springcloud-config.git
          # 使用https不用添加用户名、密码 需要设置仓库为Public
          uri: https://github.com/ordinarylq/springcloud-config.git
          # 搜索目录
          search-paths:
            - springcloud-config
          # 如果不配置的话，默认分支为master
          default-label: main
      label: main # 读取的分支

  # rabbitmq配置
  rabbitmq:
    host: 192.168.145.128
    port: 5672
    username: admin
    password: 123456

# 暴露刷新端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
  instance:
    instance-id: configCenter3344
    prefer-ip-address: true
