server:
  port: 8801
spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      # 配置要绑定的rabbitmq的服务信息
      binders:
        # 名称
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.145.128
                port: 5672
                username: admin
                password: 123456
      # 服务整合
      bindings:
        # 通道名称
        output:
          # 使用的交换机名
          destination: test-stream-exchange
          # 消息的类型，文本则设置为text/plain
          content-type: application/json
          binder: defaultRabbit
  rabbitmq:
    host: 192.168.145.128
    port: 5672
    username: admin
    password: 123456

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
  instance:
    instance-id: MsgProvider8801
    prefer-ip-address: true
