server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route01 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/discovery/**         # 断言，路径相匹配的进行路由
        - id: payment_route02
          #uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/**
#            - After=2022-08-28T11:14:01.079+08:00[GMT+08:00]
#            - Before=2022-08-28T12:14:01.079+08:00[GMT+08:00]
#            - Cookie=username,jerry
#            - Header=X-Request-Id, \d+ # 请求头要有X-Request-Id属性且值为正整数
          filters:
            - AddRequestParameter=X-Request-Id,1024 # 该过滤器工厂会在匹配的请求的请求头上添加一个参数X-Request-Id，值为1024


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
  instance:
    instance-id: gateway9527
    prefer-ip-address: true