CREATE DATABASE IF NOT EXISTS cloud2022;
USE cloud2022;

CREATE TABLE IF NOT EXISTS payment(
	id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
	SERIAL VARCHAR(200) DEFAULT '',
	PRIMARY KEY(id)
);

SELECT * FROM payment;