spring:
  # 数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 50
  # redis配置
  redis:
    jedis:
      pool:
        max-wait: 2000
        min-idle: 5
        max-active: 10
        max-idle: 10
    port: 6379
    host: 192.168.145.128

##缓存配置
#  cache:
#    type: redis
#    cache-names: redisCache
#    redis:
#      use-key-prefix: false #默认为true
#      cache-null-values: true #默认为true
#      key-prefix: #自定义前缀
#      time-to-live: 600000 #600s，默认不超时

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lq.redisdemo3.bean


# 日志配置
logging:
  level:
    root: info
    org.springframework: debug
    org.mybatis: debug


